import { CorePalette } from '../node_modules/@material/material-color-utilities/palettes/core_palette.js';
import { Scheme } from '../node_modules/@material/material-color-utilities/scheme/scheme.js';
import { argbFromHex, hexFromArgb } from '../node_modules/@material/material-color-utilities/utils/string_utils.js';
import { writeFile } from 'node:fs/promises';

// Change this one value to regenerate every Material 3 color role.
const seed = '#845401';
const source = argbFromHex(seed);
const palettes = CorePalette.of(source);

const cssName = name => `--md-sys-color-${name.replace(/[A-Z]/g, letter => `-${letter.toLowerCase()}`)}`;
const color = argb => hexFromArgb(argb);

function schemeTokens(scheme) {
  return Object.entries(scheme.toJSON()).map(([name, value]) => `  ${cssName(name)}: ${color(value)};`);
}

function surfaceTokens(isDark) {
  const tone = value => color(palettes.n1.tone(value));
  const tones = isDark
    ? { background: 6, surface: 6, surfaceDim: 6, surfaceBright: 24, surfaceContainerLowest: 4, surfaceContainerLow: 10, surfaceContainer: 12, surfaceContainerHigh: 17, surfaceContainerHighest: 22 }
    : { background: 98, surface: 98, surfaceDim: 87, surfaceBright: 98, surfaceContainerLowest: 100, surfaceContainerLow: 96, surfaceContainer: 94, surfaceContainerHigh: 92, surfaceContainerHighest: 90 };
  return Object.entries(tones).map(([name, value]) => `  ${cssName(name)}: ${tone(value)};`);
}

function block(selector, scheme, isDark) {
  const roles = new Map(schemeTokens(scheme).map(line => [line.slice(2, line.indexOf(':')), line]));
  for (const line of surfaceTokens(isDark)) roles.set(line.slice(2, line.indexOf(':')), line);
  roles.set('--md-sys-color-surface-tint', `  --md-sys-color-surface-tint: ${color(scheme.primary)};`);
  return `${selector} {\n  color-scheme: ${isDark ? 'dark' : 'light'};\n${[...roles.values()].join('\n')}\n}`;
}

const css = `/* Generated by scripts/generate-theme.mjs from Material 3 seed ${seed}. Do not edit manually. */
${block(':root', Scheme.light(source), false)}

${block('html[data-theme="dark"]', Scheme.dark(source), true)}
`;

await writeFile(new URL('../src/theme.generated.css', import.meta.url), css, 'utf8');
